[[Xorg_libXtst]]
arch = "aarch64"
git-tree-sha1 = "ddfe3981cc5879c51acfa0f7f2accde83a43f9a7"
libc = "glibc"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "139f8601cda9485793bd6ef8b337d995661ef3c1362693cfb9cf5656697b9d9e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.aarch64-linux-gnu.tar.gz"
[[Xorg_libXtst]]
arch = "aarch64"
git-tree-sha1 = "b73f70f4f4bc62e77c4a53d59c8a514aab4720ab"
libc = "musl"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "8b62f741c4f04e7c0227e2bddadd09c49af8c42f99bacd272b263f8d732f1845"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.aarch64-linux-musl.tar.gz"
[[Xorg_libXtst]]
arch = "aarch64"
git-tree-sha1 = "653eb1815179d09004e1370bb7227a272fc258bf"
os = "freebsd"

    [[Xorg_libXtst.download]]
    sha256 = "d8ac9c3d22dd454d623b2061a28915166339e21bca28fdf85039b8e4350cd17b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXtst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "738a900688a0396a1e3c2abc70242114e0f16634"
libc = "glibc"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "1e75c426e9f7b657df98a1141c4be5752d4880658687e70f4fe4abfeb18fc91c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXtst]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d08867538d61f1bbd4dca2807f1b63fc98e1b666"
libc = "musl"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "eff2636c3a3312ac8e2eb54d48de609bcbc9f69a9ae0e3d2fc00e3877bf563f8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXtst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d911d130813bcc0f47dd7f46f226e3a0de553ef"
libc = "glibc"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "72280c9707b7d2899a50763e0628b324d4aacaf203505af20909047974db1e5d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXtst]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "926ce6adeec06ce251e07f3c486517187a5770b8"
libc = "musl"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "b0f6c2702a41033f9707c57224c6da73b0657bee44a1b872651bda4688c90b30"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXtst]]
arch = "i686"
git-tree-sha1 = "33249cf9e72a1f7c743457aa8ac5893a30c8c42b"
libc = "glibc"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "8eea4239cefcfd184742805caf27f30d965c57bf83060100e64cf3462b9f8e57"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.i686-linux-gnu.tar.gz"
[[Xorg_libXtst]]
arch = "i686"
git-tree-sha1 = "54645234c57e83c378e2636faeae32d8de04e02e"
libc = "musl"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "9e047bb10cf960f94f00d084bf487b0ee1411a98716ebc10cf234e1b5bf9b5a0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.i686-linux-musl.tar.gz"
[[Xorg_libXtst]]
arch = "powerpc64le"
git-tree-sha1 = "29e17ff66080ef5972dc1a045f7ede2344669f67"
libc = "glibc"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "6b2804c2dddb73950ebbcf2b527786d72f7a4ed9592e298fc6775d08c0eb2115"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXtst]]
arch = "riscv64"
git-tree-sha1 = "4574ae0b21ac42a01e358a972bb82106a804c9f4"
libc = "glibc"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "c1356724762dd587c982ed88e422ccd6f115d47e0e297f2b729049daf14bfd41"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.riscv64-linux-gnu.tar.gz"
[[Xorg_libXtst]]
arch = "x86_64"
git-tree-sha1 = "e136226534ed7eda7d415cad54d76e096feea5ba"
libc = "glibc"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "c340e162148c9a6382176b9f42af421e2ac1ea5d923f2ee62c7340df70f8c29e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.x86_64-linux-gnu.tar.gz"
[[Xorg_libXtst]]
arch = "x86_64"
git-tree-sha1 = "2557b5baea7e109f33bf5e8247c0656e3e4fcc0e"
libc = "musl"
os = "linux"

    [[Xorg_libXtst.download]]
    sha256 = "8eecfeab9e5319e1c23c49b86835e69d9b731884e23f9fee3dd94a56b3ca65fd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.x86_64-linux-musl.tar.gz"
[[Xorg_libXtst]]
arch = "x86_64"
git-tree-sha1 = "4591b61b70b0250a916146040619889f67afdeae"
os = "freebsd"

    [[Xorg_libXtst.download]]
    sha256 = "03ef5d1b914bb85151cdb3a25f2a921b8047791646465406a75f266c0370a38a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXtst_jll.jl/releases/download/Xorg_libXtst-v1.2.5+0/Xorg_libXtst.v1.2.5.x86_64-unknown-freebsd.tar.gz"
